name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "5 1 * * *"

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php:
          - 8.2
          - 8.1
          - 8.0
          - 7.4
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: shivammathur/setup-php@2.21.2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - run: composer install

      - run: vendor/bin/phpunit --coverage-text -c phpunit.xml.dist