# Get composer
FROM composer:2.7.1 as composer

FROM php:8.1.27-fpm-bullseye

# Install libraries and PHP-Extensions that are not provided by the base image
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libfreetype6-dev=2.10.4+dfsg-1+deb11u1 \
        libjpeg62-turbo-dev=1:2.0.6-4 \
        libsnmp-dev=5.9+dfsg-4+deb11u1 \
        snmp=5.9+dfsg-4+deb11u1 \
        unzip=6.0-26+deb11u1 \
        libzip-dev=1.7.3-1 \
        git=1:2.30.2-1+deb11u2 \
        wget=1.21-1+deb11u1 \
    && docker-php-ext-install -j"$(nproc)" mysqli snmp \
    && docker-php-ext-configure gd --enable-gd --prefix=/usr --with-jpeg --with-freetype \
    && docker-php-ext-install -j"$(nproc)" gd \
    # Cleanup
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Composer setup starts here. The zip extension is required for that.
RUN docker-php-ext-install zip
COPY --from=composer /usr/bin/composer /usr/local/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1

# Install phpDocumentor
RUN wget --progress=dot:giga https://phpdoc.org/phpDocumentor.phar \
    && chmod +x phpDocumentor.phar \
    && mv phpDocumentor.phar /usr/local/bin/phpDocumentor

# Copy prepare-release.sh script
COPY ./bin/prepare-release.sh /usr/local/bin/prepare-release.sh

ENTRYPOINT ["/usr/local/bin/prepare-release.sh"]
