# Get composer
FROM composer:2.7.1 as composer

FROM php:8.1.27-fpm-bullseye

# Install libraries and PHP-Extensions that are not provided by the base image
RUN apt-get update \
    && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libsnmp-dev \
        snmp \
        unzip \
        libzip-dev \
        git \
        wget \
    && docker-php-ext-install -j$(nproc) mysqli snmp \
    && docker-php-ext-configure gd --enable-gd --prefix=/usr --with-jpeg --with-freetype \
    && docker-php-ext-install -j$(nproc) gd \
    # Cleanup
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Composer setup starts here. The zip extension is required for that.
RUN docker-php-ext-install zip
COPY --from=composer /usr/bin/composer /usr/local/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1

# Install phpDocumentor
RUN wget https://phpdoc.org/phpDocumentor.phar \
    && chmod +x phpDocumentor.phar \
    && mv phpDocumentor.phar /usr/local/bin/phpDocumentor

# Copy prepare-release.sh script
COPY ./bin/prepare-release.sh /usr/local/bin/prepare-release.sh

ENTRYPOINT ["/usr/local/bin/prepare-release.sh"]
