<?php

$FtpDomainName = "domainangeben";
$FtpServPath = "C:/Programme/Gene6 FTP Server/";


//NICHT VERÄNDERN !!! mfg Kuppe
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$NewUserFile = "NEWWEBUSER.ini";
$filename=$FtpServPath.'/Accounts/'.$FtpDomainName.'/users/'.$NewUserFile;
$filename_new=$FtpServPath.'/Accounts/'.$FtpDomainName.'/users/'.$username.'.ini';
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

?>