('signon_multiparty', '0', 'boolean', 'System-Daten', 'Wird das System für mehrere Partys verwendet?');
('signon_signonemail_subject', 'Informationsmail zur Anmeldung bei der LANparty', 'string', 'Anmeldung', 'Subjekt der eMail, die dem Teilnehmer nach seiner Registrierung gesendet wird.');
('signon_agb_targetblank', '1', 'boolean', 'Anmeldung', 'Soll der Link zu den AGB in einem neuen Fenster angezeigt werden?');
('signon_agblink', '/index.php?mod=info2&action=show_info2&submod=Regeln%20(AGB)', 'string', 'Anmeldung', 'Link zu den AGB');
('signon_volllink', '', 'string', 'Anmeldung', 'Link zu der U18-Vollmacht');
('signon_show_firstname', '2', 'signon', 'Anmeldungsfelder', 'Vorname');
('signon_show_lastname', '2', 'signon', 'Anmeldungsfelder', 'Nachname');
('signon_show_street', '1', 'signon', 'Anmeldungsfelder', 'Straße');
('signon_show_city', '1', 'signon', 'Anmeldungsfelder', 'Stadt');
('signon_show_perso', '1', 'signon', 'Anmeldungsfelder', 'Personalausweis');
('signon_show_birthday', '1', 'signon', 'Anmeldungsfelder', 'Geburtstag');
('signon_show_gender', '1', 'signon', 'Anmeldungsfelder', 'Geschlecht');
('signon_show_agb', '2', 'signon', 'Anmeldungsfelder', 'AGB Zustimmung');
('signon_show_voll', '0', 'signon', 'Anmeldungsfelder', 'U18 Zustimmung');
('signon_show_clan', '1', 'signon', 'Anmeldungsfelder', 'Clan');
('signon_show_clanurl', '1', 'signon', 'Anmeldungsfelder', 'Clanurl');
('signon_show_wwcl_id', '1', 'signon', 'Anmeldungsfelder', 'WWCL-ID');
('signon_show_ngl_id', '1', 'signon', 'Anmeldungsfelder', 'NGL-ID');
('signon_show_newsletter', '1', 'signon', 'Anmeldungsfelder', 'Newsletter Anforderung');
('signon_autocheckin', '0', 'boolean', 'Anmeldung', 'Sollen neu angemeldete User automatisch eingecheckt werden?');
('signon_autopaid', '0', 'boolean', 'Anmeldung', 'Sollen neu angemeldete User automatisch auf bezahlt gesetzt werden?');
('signon_password_mail', '1', 'boolean', 'Anmeldung', 'Dem neuen Teilnehmer sein Passwort per eMail zusenden?');
('signon_password_view', '0', 'boolean', 'Anmeldung', 'Dem neuen Teilnehmer sein Passwort anzeigen?');
('signon_autopw', '0', 'boolean', 'Anmeldung', 'Soll das Passwort automatisch generiert werden');
('signon_ask_paid_email', '1', 'boolean', 'Anmeldung', 'Soll nach der Bezahltstatusänderung die Option geboten werden, dem Benutzer eine Mail zu senden?');
('signon_alwaysagb', '0', 'boolean', 'Anmeldung', 'Soll die AGB auch angezeigt werden, wenn man nur einen Account erstellt?');
('signon_partyid', '1', 'string', 'System-Daten', 'Bitte Standart Party festlegen (Nummer muss existieren)');
('signon_showorga', '0', 'boolean', 'signon', 'Sollen Orgas mit in der Gästeliste angezeigt werden.');
('signon_last_user_box', '1', 'boolean', 'Anmeldung', 'Soll eine Box mit den zuletzt angemeldeten Benutzern angezeigt werden?');