('sys_optional_footer', '', 'string', 'System', 'Fügt den Text als weitere Fooderzeile unter dem bestehendem hinzu. (html-code)');
('sys_show_password_direct', '1', 'boolean', 'System', 'Sollen Passwörter in DIESER Übersicht in Klartext angezeigt werden?');
('sys_partyurl', 'http://www.one-network.org', 'string', 'System', 'Der Link zu der LanParty-Homepage');
('sys_party_mail', '', 'string', 'System', 'Kontaktemail der Lanparty (Webmaster)');
('sys_internet', '1', 'boolean', 'System', 'Läuft diese Version im Internet (Anmeldesystem) ?');
('sys_showdebug', '0', 'boolean', 'System', 'Sollen Debug-Mitteilungen angezeigt werden ?');
('sys_debug_allinfo', '1', 'boolean', 'System', 'Zeigt zusätzliche Debug-Informationen.');
('sys_showdebug_ftp', '0', 'boolean', 'System', 'FTP Debug Messages');
('sys_logoffdoubleusers', '0', 'boolean', 'System', 'Soll ein eingeloggter User ausgeloggt werden, wenn sich ein 2. mit diesem Account anmeldet?');
('sys_currency', 'Euro', 'string', 'System', 'Währung des Systems');
('sys_language', 'de', 'language', 'System', 'Sprache des System');
('sys_country', 'de', 'country', 'System', 'Land in dem die Party stattfindet');
('sys_barcode_on', '0', 'boolean', 'System', 'Soll das Barcodesystem verwendet werden?');
('sys_barcode_typ', 'EAN-13', 'barcode', 'System', 'Barcode-Typ der verwendet werden soll.');
('sys_compress_level', '0', 'int', 'System', 'Stärke der Seitenkompression: 0 = Kompression deaktiviert, 1 = schwach, 9 = stark');
