<?php

$gametypes = array( 'aa'       => 'America`s Army',
                    'atron'    => 'Armagetronad',
                    'bf'       => 'Battlefield 1942',
                    'bfv'      => 'Battlefield Vietnam',
                    'bf2'      => 'Battlefield 2',
                    'bf2142'   => 'Battlefield 2142',
                    'cod'      => 'Call of Duty',
                    'cod2'     => 'Call of Duty 2',
                    'cod4'     => 'Call of Duty 4',
                    'descent3' => 'Descent 3 (without gamespy)',
                    'des3gs'   => 'Descent 3 (gamespy)',
                    'd3'       => 'Doom 3',
                    'et'       => 'Enemy Territory',
                    'fear'     => 'FEAR',
                    'halo'     => 'HALO',
                    'hl_old'   => 'Half-Life / CS OLD',
                    'hl'       => 'Half-Life / CS',
                    'hl2'      => 'Half-Life 2 / CS:S',
                    'hd2'      => 'Hidden & Dangerous 2',
                    'jedi'     => 'Jedi Knight: Jedi Academy',
                    'jedi2'    => 'Jedi knight II',
                    'mohaa'    => 'Medal of Honor',
                    'nolf'     => 'No One Lives Forever',
                    'pk'       => 'Painkiller',
                    'ro'       => 'Red Orchestra',
                    'rtcw'     => 'Return to Castle Wolfenstein',
                    'rune'     => 'Rune',
                    'sof2'     => 'Soldier of Fortune 2',
                    'swat'     => 'SWAT 4',
                    'ts'       => 'Teamspeak',
                    'ut'       => 'Unreal Tournament',
                    'ut2003'   => 'Unreal Tournament 2003',
                    'ut2004'   => 'Unreal Tournament 2004',
                    'qw'       => 'Quakeworld',
                    'q1'       => 'Quake 1',
                    'q2'       => 'Quake 2',
                    'q3'       => 'Quake 3',
                    'q4'       => 'Quake 4',
                    'warsow'   => 'Warsow',
                    'vc'       => 'Vietkong',
                    'ef'       => 'Eliteforce');
?>