name: hadolint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 1 * * *"

jobs:
  hadolint:
    name: Linting (Dockerfile)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: Run hadolint on Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          config: ./.hadolint.yaml
      
      - name: Run hadolint on Dockerfile-Production-Release
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile-Production-Release
          config: ./.hadolint.yaml